export const allPosts = [
  {
    title: "Subscribe to my YouTube channel",
    total: 300,
    done: 100,
    duration: 34,
    payment: "$40",
  },
  {
    title: "Join my fitness challenge",
    total: 50,
    done: 20,
    duration: 21,
    payment: "$10",
  },
  {
    title: "Learn JavaScript in 30 days",
    total: 1000,
    done: 400,
    duration: 30,
    payment: "$100",
  },
  {
    title: "Write a blog post on AI ethics",
    total: 10,
    done: 5,
    duration: 7,
    payment: "$20",
  },
  {
    title: "Complete my survey on climate change",
    total: 200,
    done: 150,
    duration: 5,
    payment: "$5",
  },
  {
    title: "Design a logo for my startup",
    total: 50,
    done: 30,
    duration: 14,
    payment: "$50",
  },
  {
    title: "Translate document from English to Spanish",
    total: 20,
    done: 10,
    duration: 3,
    payment: "$15",
  },
  {
    title: "Edit wedding video",
    total: 1,
    done: 1,
    duration: 8,
    payment: "$200",
  },
  {
    title: "Teach piano lessons",
    total: 12,
    done: 6,
    duration: 60,
    payment: "$240",
  },
  {
    title: "Babysit for 3 hours",
    total: 5,
    done: 3,
    duration: 3,
    payment: "$30",
  },
  {
    title: "Create social media content for a week",
    total: 7,
    done: 7,
    duration: 7,
    payment: "$70",
  },
  {
    title: "Build a website",
    total: 1,
    done: 1,
    duration: 30,
    payment: "$500",
  },
  {
    title: "Proofread my thesis",
    total: 100,
    done: 50,
    duration: 14,
    payment: "$80",
  },
  {
    title: "Photograph a family portrait session",
    total: 3,
    done: 3,
    duration: 2,
    payment: "$150",
  },
  {
    title: "Tutor math for high school students",
    total: 10,
    done: 8,
    duration: 10,
    payment: "$200",
  },
  {
    title: "Paint a mural",
    total: 1,
    done: 1,
    duration: 20,
    payment: "$300",
  },
  {
    title: "Cook a gourmet meal for two",
    total: 2,
    done: 2,
    duration: 3,
    payment: "$100",
  },
  {
    title: "Write a short story",
    total: 1,
    done: 1,
    duration: 7,
    payment: "$50",
  },
  {
    title: "Assemble IKEA furniture",
    total: 3,
    done: 3,
    duration: 5,
    payment: "$60",
  },
  {
    title: "Run a marathon",
    total: 1,
    done: 0,
    duration: 180,
    payment: "None",
  },
];

export const proofs = [
  {
    id: 1,
    key: "proof1",
    title: "Proof 1",
  },
  {
    id: 2,
    key: "proof2",
    title: "Proof 2",
  },
  {
    id: 3,
    key: "proof3",
    title: "Proof 3",
  },
  {
    id: 4,
    key: "proof4",
    title: "Proof 4",
  },
];

export const proofTypes = [
  {
    id: 1,
    type: "screenshot",
    title: "Screenshot",
  },
  {
    id: 2,
    type: "text",
    title: "Text",
  },
];
